[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "py416"
version = "0.2"
authors = [
  { name="Ezio416", email="ezezio416@gmail.com" },
]
description = "don't question my methods"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ezio416/py416"
"Bug Tracker" = "https://github.com/ezio416/py416/issues"